config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  resources :undo, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/soft_delete.rb
# frozen_string_literal: true

module SoftDelete
  extend ActiveSupport::Concern

  included do
    scope :active, -> { where(deleted_at: nil) }
    scope :deleted, -> { where.not(deleted_at: nil) }
  end

  def schedule_destroy
    timeout = defined?(UNDO_TIMEOUT) ? UNDO_TIMEOUT : 8
    update(deleted_at: Time.zone.now.utc)
    DeleteWorker.perform_in(timeout.seconds + 5.seconds, self.class.name, id)
  end

  def recover
    update(deleted_at: nil)
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  UNDO_TIMEOUT = 8
  include SoftDelete
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success

  private

  def destroy_with_undo_response(record:, job_id:, redirect:)
    respond_to do |format|
      format.html do
        flash[:success] = undo_flash_message(klass: record.class, job_id: job_id)
        redirect_to redirect
      end
      format.turbo_stream do
        if params[:redirect]
          flash[:success] = undo_flash_message(klass: record.class, job_id: job_id)
          redirect_to redirect
        else
          flash.now[:success] = undo_flash_message(klass: record.class, job_id: job_id, inline: true)
          render 'undo/destroy', locals: { record: record }
        end
      end
    end
  end

  def undo_flash_message(klass:, job_id:, inline: nil)
    timeout = defined?(klass::UNDO_TIMEOUT) ? klass::UNDO_TIMEOUT : 10

    {
      title: "#{klass.model_name.human} was removed",
      body: 'You can recover it using the undo action below.',
      timeout: timeout, countdown: true,
      action: {
        url: undo_path(job_id, inline: inline),
        method: 'delete',
        name: 'Undo'
      }
    }
  end
end

app/controllers/concerns/destroy_with_undo_response.rb
# frozen_string_literal: true

module DestroyWithUndoResponse
  extend ActiveSupport::Concern

  private

  def destroy_with_undo_response(record:, job_id:, redirect:)
    respond_to do |format|
      format.html do
        flash[:success] = undo_flash_message(klass: record.class, job_id: job_id)
        redirect_to redirect
      end
      format.turbo_stream do
        if params[:redirect]
          flash[:success] = undo_flash_message(klass: record.class, job_id: job_id)
          redirect_to redirect
        else
          flash.now[:success] = undo_flash_message(klass: record.class, job_id: job_id, inline: true)
          render 'undo/destroy', locals: { record: record }
        end
      end
    end
  end

  def undo_flash_message(klass:, job_id:, inline: nil)
    timeout = defined?(klass::UNDO_TIMEOUT) ? klass::UNDO_TIMEOUT : 10

    {
      title: "#{klass.model_name.human} was removed",
      body: 'You can recover it using the undo action below.',
      timeout: timeout, countdown: true,
      action: {
        url: undo_path(job_id, inline: inline),
        method: 'delete',
        name: 'Undo'
      }
    }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include DestroyWithUndoResponse

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.active.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        flash = {
          title: "#{@post.title} was successfully created.",
          body: 'You can go to the edit page with the button below.',
          action: { url: edit_post_path(@post), method: 'get', name: 'Edit' }
        }
        format.html { redirect_to posts_url, success: flash }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash = {
          title: "#{@post.title} was successfully updated.",
          body: 'You can view it with the button below.',
          action: { url: post_path(@post), method: 'get', name: 'View' }
        }
        format.html { redirect_to posts_url, success: flash }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    post = Post.active.find(params[:id])
    job_id = post.schedule_destroy
    destroy_with_undo_response(record: post, job_id: job_id, redirect: posts_path)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title)
  end
end

app/controllers/undo_controller.rb
# frozen_string_literal: true

require 'sidekiq/api'

class UndoController < ApplicationController
  def destroy
    job = Sidekiq::ScheduledSet.new.find_job(params[:id])
    done = recover_record(job)

    if done
      response = prepare_response(job)
      respond_to do |format|
        format.json { render json: response, status: :ok }
      end
    else
      head :unprocessable_entity
    end
  end

  private

  def recover_record(job)
    return false unless job

    job.delete
    record = job.item['args'][0].constantize.find(job.item['args'][1])
    record.recover

    true
  end

  def prepare_response(job)
    inline = params[:inline].presence ? true : false
    {
      message: inline ? 'Done!' : 'Done! Reloading the page...',
      inline: inline,
      dom_id: ("#{job.item["args"][0].underscore}_#{job.item["args"][1]}" if job)
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Modern Rails Flash Messages</title>
    <meta name="description" content="Modern Rails flash messages with Rails, ViewComponent, Stimulus and Tailwind CSS">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <div class="min-h-screen bg-white">
      <nav class="bg-white border-b border-gray-200">
        <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex justify-between h-16">
            <div class="flex">
              <div class="flex-shrink-0 flex items-center">
                <a href="<%= root_path %>">Modern Rails flash messages</a>
              </div>
              <div class="hidden sm:-my-px sm:ml-6 space-x-8 sm:flex">
                <a href="<%= posts_path %>" class="inline-flex items-center px-1 pt-1 border-b-2 border-indigo-500 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-indigo-700 transition duration-150 ease-in-out">
                  Posts
                </a>
                <a href="https://dev.to/citronak/series/8559" target="_blank" class="inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-indigo-700 transition duration-150 ease-in-out">
                  Read how to&nbsp;<i class="fas fa-external-link-alt"></i>
                </a>
              </div>
            </div>
            <div class="flex sm:hidden">
              <a href="https://dev.to/citronak/series/8559" target="_blank" title="Read how to" class="inline-flex items-center px-1 pt-1 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-indigo-700 transition duration-150 ease-in-out">
                <i class="fas fa-external-link-alt"></i>
              </a>
            </div>
          </div>
        </div>
      </nav>

      <div class="py-10">
        <header>
          <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold leading-tight text-gray-900">
              <%= yield(:title) %>
            </h1>
          </div>
        </header>
        <main>
          <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
            <div class="px-4 py-8 sm:px-0">
              <%= yield %>
            </div>
          </div>
        </main>
      </div>
    </div>

    <div class="fixed inset-0 px-4 py-6 pointer-events-none sm:p-6 sm:items-start sm:justify-end">
      <div id="notifications" class="flex flex-col items-end justify-center">
        <% flash.each do |type, data| %>
          <%= render NotificationComponent.new(type: type, data: data) %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label class="block">
    <span class="text-gray-700">Title</span>
    <%= form.text_field :title, class: 'form-input mt-1 block w-64' %>
  </label>

  <div class="mt-6">
    <span class="inline-flex rounded-md shadow-sm">
      <%= form.button type: 'submit', class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150' %>
    </span>
    <%= link_to 'Back', posts_path, class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-50 focus:outline-none focus:border-indigo-300 focus:shadow-outline-indigo active:bg-indigo-200 transition ease-in-out duration-150' %>
    <% if @post.persisted? %>
      <%= link_to 'Delete', post_path(@post, redirect: true), method: :delete, class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition ease-in-out duration-150' %>
    <% end %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<% content_for :title, 'Editing Post' %>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% content_for :title, 'Posts' %>

<% if @posts.any? %>
  <div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead>
              <tr>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                  Title
                </th>
                <th class="px-6 py-3 bg-gray-50" colspan="3"></th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% @posts.each do |post| %>
                <tr id="<%= dom_id(post) %>">
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900"><%= post.title %></td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium"><%= link_to 'Show', post, class: 'text-indigo-600 hover:text-indigo-900' %></td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium"><%= link_to 'Edit', edit_post_path(post), class: 'text-indigo-600 hover:text-indigo-900' %></td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium"><%= link_to 'Destroy', post, method: :delete, class: 'text-red-600 hover:text-red-900' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="mt-8">
  <span class="inline-flex rounded-md shadow-sm3">
    <%= link_to 'New Post', new_post_path, class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150' %>
  </span>
</div>

app/views/posts/new.html.erb
<% content_for :title, 'New Post' %>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>

<span class="inline-flex rounded-md shadow-sm mt-3">
  <%= link_to 'Edit', edit_post_path(@post), class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150' %>
</span>

<%= link_to 'Back', posts_path, class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-50 focus:outline-none focus:border-indigo-300 focus:shadow-outline-indigo active:bg-indigo-200 transition ease-in-out duration-150' %>
<%= link_to 'Delete', post_path(@post, redirect: true), method: :delete, class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition ease-in-out duration-150' %>

app/views/undo/destroy.turbo_stream.erb
<turbo-stream action="addclass" target="<%= dom_id(record) %>">
  <template>hidden</template>
</turbo-stream>

<% flash.each do |type, data| %>
  <%= turbo_stream.prepend('notifications', render(NotificationComponent.new(type: type, data: data))) %>
<% end %>